before_script:
  - "mysql -e 'create database sequelize_test;'"
  - "psql -c 'create database sequelize_test;' -U postgres"

script:
  - "make test"

notifications:
  email: false

env:
  - DB=mysql DIALECT=mysql
  - DB=mysql DIALECT=postgres
  - DB=mysql DIALECT=postgres-native
  - DB=mysql DIALECT=sqlite

language: node_js

node_js:
  - "0.8"
  - "0.10"

branches:
  only:
    - master
    - milestones/2.0.0
